### ISSUE TITLE
chữ u trong chữ uỷ là chữ u thường?

### ISSUE THREAD

**Issue by thuvh** [vncorenlp/VnCoreNLP#11]
https://github.com/vncorenlp/VnCoreNLP/blob/8fa8cafeafb87ad11860b0025dc528ca48261106/src/main/java/vn/corenlp/wordsegmenter/Utils.java#L122

**Comment by vncorenlp** [comment]
It's an upper-case character "U". See line 119, that's a lower-case "u".
