### ISSUE TITLE
Retrain word segmentation guideline

### ISSUE THREAD

**Issue by binhna** [vncorenlp/VnCoreNLP#14]
Hi, I have read your [VnCoreNLP](http://aclweb.org/anthology/N18-5012) but I didn't see any documentation for retraining the RDRsegmenter. Could you please put more details on how to retrain this and make the "rules" automatically from **"gold standard corpus"** and **"raw corpus"**?

Many thanks

**Comment by vncorenlp** [comment]
@datquocnguyen will probably do it when he has some spare time.
Best,

**Comment by datquocnguyen** [comment]
Done!
