### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by bratao** [vncorenlp/VnCoreNLP#15]
Hello,

Thank you for this awesome project. @datquocnguyen @vncorenlp 

I'm very interested in your Dynamic Feature induction for NER. Can you please provide the source code? At least the dynamic feature induction part. 

I can only find the compiled jar.

**Comment by vncorenlp** [comment]
Our NER is based on NLP4J (https://emorynlp.github.io/nlp4j). You can find the source code at https://github.com/emorynlp/nlp4j
