### ISSUE TITLE
Chunk tagging

### ISSUE THREAD

**Issue by TQuy** [vncorenlp/VnCoreNLP#16]
I realized that changing the word segmentation of VLSP 2016 NER shared task dataset makes it hard to measure the performance of the model. The issue can also be seen from the paper  "Attentive Neural Network for Named Entity Recognition in Vietnamese". 
![image](https://user-images.githubusercontent.com/45731304/58752653-e3247680-84dc-11e9-88df-9246e5bbf3a4.png)
As a result, I want to do POS and CHUNK tagging with pre-word segmentation, is that possible

**Comment by vncorenlp** [comment]
Hi, VnCoreNLP does not support chunking (simply because chunking is not a serious and useful task, and also it can be implicitly inferred from (dependency) parsed tree).
