### ISSUE TITLE
word segmentation without sentence segmentation?

### ISSUE THREAD

**Issue by trangtv57** [vncorenlp/VnCoreNLP#17]
I want just word segmentation my data, not split sentence by "." or other punctuation. But I don't know what's option for this. Or do you need sentence segmentation for word segmentation better ?
Thanks you

**Comment by tienthanhdhcn** [comment]
Yes, it is. The process is to segment the tokenized text into sentences first and then segment the sentences into words. To meet your need, you can write some simple snippet in Java or Python to process the output of the model.
Cheers,
T
