### ISSUE TITLE
How to Use toolkit as a service for Python users

### ISSUE THREAD

**Issue by manhnguyenquoc** [vncorenlp/VnCoreNLP#18]
Hi, 

Thank for this awesome toolkit @vncorenlp ,

Could you please show me how to run your toolkit as a service so I can send request to it when using python?

I follow the instruction in [this link](https://github.com/vncorenlp/VnCoreNLP#use-as-a-service-recommended) but when I enter the command `vncorenlp -Xmx2g E:\Data\Projects\MobiFone5\NLP\VnCoreNLP-master\VnCoreNLP-1.1.jar -p 9000 -a "wseg,pos,ner,parse"` into command prompt, it returns _'vncorenlp' is not recognized as an internal or external command, operable program or batch file._

How can I run this command properly?

![command prompt](https://user-images.githubusercontent.com/22399058/62760834-33a4eb00-baaf-11e9-850e-f25d08bb23c1.PNG)

**Comment by qhungngo** [comment]
Hi,

This message means that the OS can not understand/find vncorenlp.
According to guide, you might run install command:
`pip3 install vncorenlp`
Then, in python you can check the location of lib by code:
```
import sysconfig
sysconfig.get_paths()['purelib']
```
Output can be: C:\\ProgramData\\Anaconda3\\Lib\\site-packages
So, the excute file will be here:
`c:\ProgramData\Anaconda3\Scripts\vncorenlp.exe`
And the python scrip will be here: 
`c:\ProgramData\Anaconda3\Lib\site-packages\vncorenlp\vncorenlp.py` 

You can replace vncorenlp by c:\ProgramData\Anaconda3\Scripts\vncorenlp.exe, and even update python file to change configure for JAVA and server port.

Good luck.
