### ISSUE TITLE
Không thể sử dụng được tookit.

### ISSUE THREAD

**Issue by huynhminhphuc** [vncorenlp/VnCoreNLP#22]
Mình đã làm theo hướng dẫn của tác giả, nhưng khi chạy đến đoạn:

`annotator = VnCoreNLP(address="http://127.0.0.1", port=9000)`

thì mình không thể chạy tiếp được, code bị treo ngay chỗ này.
Mình đổi lại thành

`annotator = VnCoreNLP()`

cũng không chạy được luôn.
Mình cũng thấy nhiều bạn phản hồi là chạy không được trên diễn đàn machinelearningcoban.
Mong nhận được phản hồi từ tác giả.

Xin cám ơn

**Comment by vncorenlp** [comment]
It works smoothly! Please carefully follow the instructions! 


## Installation <a name="install"></a>

- `Python 3.4+` if using  a Python wrapper of VnCoreNLP. To install this wrapper, users have to run the following command:

    ``$ pip3 install vncorenlp`` 
   
    
- `Java 1.8+` 
- File  `VnCoreNLP-1.1.1.jar` (27MB) and folder `models` (115MB) are placed in the same working folder.



## Usage for Python users <a name="python"></a>

### Use as a service

**Assume that the Python wrapper of VnCoreNLP is already installed via: ``$ pip3 install vncorenlp``**

1. Run the following command: 

    ``$ vncorenlp -Xmx2g <FULL-PATH-to-VnCoreNLP-jar-file> -p 9000 -a "wseg,pos,ner,parse"``
    
    The service is now available at ``http://127.0.0.1:9000``.

2. Use the service in your `python` code:

```python
from vncorenlp import VnCoreNLP
annotator = VnCoreNLP(address="http://127.0.0.1", port=9000) 
```


### Use without the service (If you cannot follow the above 2 steps!)

```python
from vncorenlp import VnCoreNLP
annotator = VnCoreNLP("<FULL-PATH-to-VnCoreNLP-jar-file>", annotators="wseg,pos,ner,parse", max_heap_size='-Xmx2g')

**Comment by tienthanhdhcn** [comment]
@huynhminhphuc the _python_ library is only a wrapper for our Java-based VnCoreNLP. So you still must download the _VnCoreNLP-1.1.1.jar_ and the _models_ folder and follow the instruction above before using it in _python_

**Comment by hosjiu1702** [comment]
> @huynhminhphuc the _python_ library is only a wrapper for our Java-based VnCoreNLP. So you still must download the _VnCoreNLP-1.1.1.jar_ and the _models_ folder and follow the instruction above before using it in _python_

so if we just wanna use WS only, will we need to download all of the subfolders (here 4) under `models/`?

IMO, I think it makes more sense if we just download folder(s) which required for our need, which in this case is `wordsegmenter/`

**Comment by datquocnguyen** [comment]
@hosjiu1702 for WS only, you can simply download the corresponding folder under models. See: https://github.com/VinAIResearch/PhoBERT#vncorenlp
