### ISSUE TITLE
Multiple requests for pipeline

### ISSUE THREAD

**Issue by dohoangminhquan** [vncorenlp/VnCoreNLP#26]
I'm trying to use VnCoreNLP for multiple requests purpose.

Supposed I got something like this:

        String[] annotators = {"wseg", "pos", "ner", "parse"};
        pipeline = new VnCoreNLP(annotators);

I tried to use the variable pipeline to annotate multiple annotations at a time. As the result it causes 2 exceptions: ConcurrentModificationException and ArrayIndexOutOfBound.

I would like to know if the lib support multi-thread or you want it to be single-thread only?

Thanks

**Comment by tienthanhdhcn** [comment]
Hi, I haven't tested VnCoreNLP with multithreading but it seems NOT to natively support multithreading. Please can you provide the code to reproduce the errors? 

For a quick solution, you can create multiple pipelines and use one for each thread. If you use Python, you also can create multiple services and use each service to handle one thread. 

Alternatively, you can split the input text into separated files and call VnCoreNLP from the command line to process the files separately and simultaneously.

**Comment by dohoangminhquan** [comment]
Hi,

Creating multiple pipelines is not a preferred solution as it takes long time to load recourse, high memory footprint and we have to manage pipeline ourselves. As the result, I would like to create just 1 pipeline that use the same resources to serve multiple requests.

Split input text into many files and use commandline to process files independently does not work as well as each process (commandline) will load resource separately and take time.

I pasted my code that call VnCoreNLP here for you to have a look:

    public static void main(String[] args) throws IOException {
        String[] annotators = {"wseg", "pos", "ner", "parse"};
        pipeline = new VnCoreNLP(annotators);
        for (int i=0;i<10;i++) {
            Thread thread = new Thread(){
                public void run(){
                    Annotation annotation = new Annotation("Covid-19 Nhiều chuyên gia kiến nghị cho học sinh nghỉ thêm 1-2 tháng");
                    try {
                        pipeline.annotate(annotation);
                    }
                    catch (Exception e) {
                         System.out.println(e);
                    }
                    System.out.println("Thread Running ");
                }
            };
            thread.start();
        }
    }

The result will be: 

2020-03-14 23:03:20 INFO  WordSegmenter:24 - Loading Word Segmentation model
2020-03-14 23:03:20 INFO  PosTagger:21 - Loading POS Tagging model
2020-03-14 23:03:24 INFO  NerRecognizer:33 - Loading NER model
2020-03-14 23:03:34 INFO  DependencyParser:31 - Loading Dependency Parsing model
java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
Thread Running 
Thread Running 
java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
Thread Running 
Thread Running 
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
Thread Running 
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
Thread Running 
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
Thread Running 
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
Thread Running 
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
Thread Running 
Thread Running 

Thank you for your time
