### ISSUE TITLE
add dependency maven

### ISSUE THREAD

**Issue by nguyentheanhhnvntd** [vncorenlp/VnCoreNLP#3]
Hello, I'm glad to use VNCoreNLP but I have issue when import this lib into other project. I want to use maven dependency to use the lib in a maven project. Can you suggest me how to do this ?

Many thanks !!

**Comment by datquocnguyen** [comment]
Hi, we currently do not support a maven release. 
You can simply use the .jar file as an external lib.
<img width="1552" alt="eclipse" src="https://user-images.githubusercontent.com/2412555/34871224-f412839a-f7e0-11e7-9a83-898e49647999.png">

**Comment by nguyentheanhhnvntd** [comment]
Hope you'll support maven soon.
Thank you.

**Comment by claeyzre** [comment]
Thanks for the great work guys, indeed that would be great if there was a maven release !
