### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by luan123z** [vncorenlp/VnCoreNLP#32]
I've got the timed out error while trying to run with these annotators="wseg,pos,ner,parse"
If I set the annotators="wseg", it runs fine.

![image](https://user-images.githubusercontent.com/19511189/92071163-32d8a880-edd8-11ea-85ec-7a21ba8a0c93.png)

**Comment by luan123z** [comment]
Hello, any updates?

**Comment by datquocnguyen** [comment]
I had no idea what happened. You might recompile the .jar vncorenlp file. 
Please recompile the .jar vncorenlp file with `mvn clean` and then `mvn install`
