### ISSUE TITLE
Tokenizer thay đổi từ gốc

### ISSUE THREAD

**Issue by nic9lif3** [vncorenlp/VnCoreNLP#33]
Chào @daiquocnguyen,

Mình có một vấn đề khi tokenizer đó là kết quả của token sẽ khác so với từ gốc. Ví dụ từ Thanh Hóa thì nó token ra Thanh_Hoá. Mình có thể fix được cái này không nhỉ.

**Comment by datquocnguyen** [comment]
This is not an issue w.r.t. vncorenlp.

**Comment by datquocnguyen** [comment]
If you really meant: `Hóa` be converted to `Hoá`, then please see: https://github.com/vncorenlp/VnCoreNLP/issues/39
