### ISSUE TITLE
Unable to create server if NER is used

### ISSUE THREAD

**Issue by sparkkid1234** [vncorenlp/VnCoreNLP#36]
Hey guys, thanks for the amazing work! I'm using the python wrapper of this project and currently having some trouble using NER. If I only use wseg and pos tagger, then it works fine, but once I added NER, it's now stuck at this [line](https://github.com/dnanhkhoa/python-vncorenlp/blob/ea5c59284d739564a99ba2f1efc37fd388770ec5/vncorenlp/vncorenlp.py#L78), which to my understanding means no server is available. Weird thing is it works fine if I only use wseg and pos tagger, and this only happens if I add NER. Thanks!

**Comment by datquocnguyen** [comment]
It might be relevant to the out-of-memory issue: https://github.com/vncorenlp/VnCoreNLP/issues/31#issuecomment-751993576
