### ISSUE TITLE
Resources to POS corpus (mapping table)

### ISSUE THREAD

**Issue by nicnguyen3103** [vncorenlp/VnCoreNLP#37]
Thanks for creating such a wonderful tool. However, I cannot seem to find the POS tag corpus and mapping table anywhere, therefore the result of POS tagging is a bit confusing to me. Could you guide me to the resources that you use to make the POS tag label? 
Thanks

**Comment by datquocnguyen** [comment]
https://vlsp.org.vn/resources-vlsp2013
