### ISSUE TITLE
Add new word to VnCoreNLP

### ISSUE THREAD

**Issue by ngovanminh3232** [vncorenlp/VnCoreNLP#44]
I want to add new word to tokenizer
Example: FIS Bank -> FIS_Bank
Are you show me train VnCoreNLP?
Thank you

**Comment by datquocnguyen** [comment]
You can add that word into [the Vocabulary.java file](https://github.com/vncorenlp/VnCoreNLP/blob/62bbc58fe5d113c898eae112656be97dcf50b3a0/src/main/java/vn/corenlp/wordsegmenter/Vocabulary.java#L148): either `COUNTRY_L_NAME.add("fis bank");` or `VN_LOCATIONS.add("fis bank");`, then recompile the whole toolkit via terminal by using: `mvn clean install`.
