### ISSUE TITLE
Issue with download VnCoreNLP model

### ISSUE THREAD

**Issue by hhiep1504** [vncorenlp/VnCoreNLP#46]
![image](https://user-images.githubusercontent.com/114068499/231826464-88578898-f65d-4237-8ea0-8258879fbd10.png)
I thought I downloaded the VnCoreNLP model with the code line 5 in my python file? How can I fix this?

![image](https://user-images.githubusercontent.com/114068499/231827268-2af54db1-f82c-4218-b322-afc8fc7dead8.png)

**Comment by datquocnguyen** [comment]
`rdrsegmenter = py_vncorenlp.VnCoreNLP(annotators=["wseg"], save_dir='/absolute/path/to/vncorenlp')`
In your case, `save_dir` should always be C:\\Users\hoang\Documents\models
