### ISSUE TITLE
Add builders with specific paths for models

### ISSUE THREAD

**Issue by claeyzre** [vncorenlp/VnCoreNLP#5]
Hello,

Thanks for the great work,

Using it at a dependency from a project I can't initialize the WordSegmenter, NerRecognizer, because my "user.dir" is different from the root of VnCoreNLP, (example [here](https://github.com/vncorenlp/VnCoreNLP/blob/master/src/main/java/vn/corenlp/ner/NerRecognizer.java#L37)). So the models appears to be not found. 

Would it be possible to use a write a Builder for classes like WordSegmenter, NerRecognizer .. that takes a property file to ease models loading and dependency management, a bit like StanfordCoreNLP to separate the code from the resources ? I would be happy to contribute if it's possible. 

Thanks,

**Comment by vncorenlp** [comment]
Thanks for your comment. 
We will consider your comment in our next vncorenlp release.
