### ISSUE TITLE
what kind of model for Ner task?

### ISSUE THREAD

**Issue by doannam020293** [vncorenlp/VnCoreNLP#6]
Thank you for completely awesome model. But I wanna deal in depth with model
Did you use CRF, or LSTM, and what feature use for this model? Do you have any paper in detail?
Many thanks

**Comment by tienthanhdhcn** [comment]
Hi @doannam020293 

Thank you for your consideration.

Our NER model is a feature-based model, in which we apply a dynamic feature induction model that automatically optimizes feature combinations. The feature set includes word form, word shape, POS tag, word embedding, etc. 

We also compared our feature-based NER model to neural network-based models, such as BiLSTM-CRF. The comparison results and your needed information can be found in our paper available at https://arxiv.org/pdf/1801.01331.pdf

Hope it helps,
Cheers,
VnCoreNLP Team
