### ISSUE TITLE
[end and start of tokens]

### ISSUE THREAD

**Issue by claeyzre** [vncorenlp/VnCoreNLP#9]
Hi,

StanfordCoreNLP has a lot of very convenient information contained in tokens, including the positions of the tokens in the original [sentence](https://nlp.stanford.edu/nlp/javadoc/javanlp-3.5.0/edu/stanford/nlp/ling/AbstractCoreLabel.html), materialized by .beginPosition and .endPosition.

Would it be possible to get the same kind of information for VnCoreNLP Token or Word ? 

Thanks

**Comment by vncorenlp** [comment]
VnCoreNLP currently does not support that.
Best regards,
